import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ImpactData {
  totalKgDonated: number;
  mealsProvided: number;
  co2Saved: number;
  waterSaved: number;
  energySaved: number;
  treesEquivalent: number;
  carbonCredits: number;
}

interface CarbonCreditData {
  totalCredits: number;
  pendingCredits: number;
  tradedCredits: number;
  totalValue: number;
  credits: Array<{
    id: string;
    amount: number;
    source: string;
    status: string;
    createdAt: string;
    listingTitle?: string;
  }>;
}

export function generateImpactReportPDF(
  data: ImpactData,
  userName: string = "Donor"
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(34, 197, 94); // Green
  doc.rect(0, 0, pageWidth, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("AnnaDaan", 20, 20);

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("Impact Report", 20, 32);

  // User info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text("Generated for: " + userName, 20, 55);
  doc.text("Date: " + new Date().toLocaleDateString("en-IN"), 20, 62);

  // Main stats
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Your Impact Summary", 20, 80);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  // Use ASCII-safe text for PDF (avoid Unicode subscripts)
  const stats = [
    ["Total Food Donated", data.totalKgDonated.toLocaleString() + " kg"],
    ["Meals Provided", data.mealsProvided.toLocaleString()],
    ["CO2 Emissions Saved", data.co2Saved.toFixed(1) + " kg"],
    ["Water Saved", (data.waterSaved / 1000).toFixed(1) + " kL"],
    ["Energy Saved", data.energySaved.toFixed(1) + " kWh"],
    ["Trees Equivalent", data.treesEquivalent.toString()],
    ["Carbon Credits Earned", data.carbonCredits.toFixed(2)],
  ];

  autoTable(doc, {
    startY: 90,
    head: [["Metric", "Value"]],
    body: stats,
    theme: "striped",
    headStyles: { fillColor: [34, 197, 94] },
    styles: { fontSize: 11 },
  });

  // Environmental impact section
  const finalY = (doc as any).lastAutoTable.finalY + 20;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Environmental Impact", 20, finalY);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);

  // Use ASCII-safe bullet points and text
  const impactText = [
    "By donating " + data.totalKgDonated + " kg of food, you have:",
    "- Prevented " + data.co2Saved.toFixed(1) + " kg of CO2 from entering the atmosphere",
    "- Saved " + (data.waterSaved / 1000).toFixed(1) + " kiloliters of water",
    "- Conserved " + data.energySaved.toFixed(1) + " kWh of energy",
    "- Made an impact equivalent to planting " + data.treesEquivalent + " trees",
    "",
    "Thank you for being part of the solution to food waste!",
  ];

  let yPos = finalY + 10;
  impactText.forEach((line) => {
    doc.text(line, 20, yPos);
    yPos += 7;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "This report was generated by AnnaDaan - Reducing food waste, one meal at a time.",
    pageWidth / 2,
    285,
    { align: "center" }
  );

  return doc;
}

export function generateCarbonCreditPDF(
  data: CarbonCreditData,
  userName: string = "Donor"
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(34, 197, 94);
  doc.rect(0, 0, pageWidth, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("AnnaDaan", 20, 20);

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("Carbon Credits Statement", 20, 32);

  // User info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text("Account Holder: " + userName, 20, 55);
  doc.text("Statement Date: " + new Date().toLocaleDateString("en-IN"), 20, 62);

  // Summary
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Account Summary", 20, 80);

  const summary = [
    ["Total Credits Earned", data.totalCredits.toFixed(2)],
    ["Pending Verification", data.pendingCredits.toFixed(2)],
    ["Credits Traded", data.tradedCredits.toFixed(2)],
    ["Total Value (INR)", "Rs. " + data.totalValue.toLocaleString()],
  ];

  autoTable(doc, {
    startY: 90,
    head: [["Description", "Amount"]],
    body: summary,
    theme: "striped",
    headStyles: { fillColor: [34, 197, 94] },
  });

  // Transaction history
  const finalY = (doc as any).lastAutoTable.finalY + 20;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Transaction History", 20, finalY);

  const transactions = data.credits.map((c) => [
    new Date(c.createdAt).toLocaleDateString("en-IN"),
    c.listingTitle || c.source,
    c.status,
    "+" + c.amount.toFixed(2),
  ]);

  autoTable(doc, {
    startY: finalY + 10,
    head: [["Date", "Source", "Status", "Credits"]],
    body: transactions,
    theme: "striped",
    headStyles: { fillColor: [34, 197, 94] },
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Carbon credits are verified based on food waste prevented. 1 kg food waste = 2.5 kg CO2 equivalent.",
    pageWidth / 2,
    285,
    { align: "center" }
  );

  return doc;
}

export function generateCollectorEarningsPDF(
  data: {
    totalEarnings: number;
    thisMonth: number;
    carbonCredits: number;
    transactions: Array<{
      type: string;
      amount: number;
      date: string;
      status: string;
    }>;
  },
  userName: string = "Collector"
): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(34, 197, 94);
  doc.rect(0, 0, pageWidth, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("AnnaDaan", 20, 20);

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text("Earnings Statement", 20, 32);

  // User info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text("Collector: " + userName, 20, 55);
  doc.text("Statement Date: " + new Date().toLocaleDateString("en-IN"), 20, 62);

  // Summary
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Earnings Summary", 20, 80);

  const summary = [
    ["Total Earnings", "Rs. " + data.totalEarnings.toLocaleString()],
    ["This Month", "Rs. " + data.thisMonth.toLocaleString()],
    ["Carbon Credits", data.carbonCredits.toString()],
    ["Carbon Credit Value", "Rs. " + (data.carbonCredits * 150).toLocaleString()],
  ];

  autoTable(doc, {
    startY: 90,
    head: [["Description", "Amount"]],
    body: summary,
    theme: "striped",
    headStyles: { fillColor: [34, 197, 94] },
  });

  // Transaction history
  const finalY = (doc as any).lastAutoTable.finalY + 20;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Recent Transactions", 20, finalY);

  const transactions = data.transactions.map((t) => [
    new Date(t.date).toLocaleDateString("en-IN"),
    t.type,
    t.status,
    "Rs. " + t.amount.toLocaleString(),
  ]);

  autoTable(doc, {
    startY: finalY + 10,
    head: [["Date", "Type", "Status", "Amount"]],
    body: transactions,
    theme: "striped",
    headStyles: { fillColor: [34, 197, 94] },
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "This is a computer-generated statement from AnnaDaan platform.",
    pageWidth / 2,
    285,
    { align: "center" }
  );

  return doc;
}
